[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

rpc_endpoints = { Avalanche = "https://rpc.ankr.com/avalanche" }

[profile.default.invariant]
call_override = false
fail_on_revert = true
depth = 100
runs = 5000
seed  = '42'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config