[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[fuzz]
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 50000
seed  = '42'
depth = 25
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config